/*{
 "DESCRIPTION": "Winamp's Milkdrop visualiser, dancing to whatever your computer is playing. Each key press is a beat the visuals pulse to. Pick one preset in Adjust, or let it change on its own; the Background Preset action switches them too. Drawn by projectM (LGPL-2.1) with Butterchurn's preset pack (MIT).",
 "RENDERER": "projectM",
 "INPUTS": [
  {
   "NAME": "preset",
   "TYPE": "long",
   "LABEL": "Preset",
   "DEFAULT": 0,
   "PRESET": true,
   "VALUES": [
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    27,
    28,
    29,
    30,
    31,
    32,
    33,
    34,
    35,
    36,
    37,
    38,
    39,
    40,
    41,
    42,
    43,
    44,
    45,
    46,
    47,
    48,
    49,
    50,
    51,
    52,
    53,
    54,
    55,
    56,
    57,
    58,
    59,
    60,
    61,
    62,
    63,
    64,
    65,
    66,
    67,
    68,
    69,
    70,
    71,
    72,
    73,
    74,
    75,
    76,
    77,
    78,
    79,
    80,
    81,
    82,
    83,
    84,
    85,
    86,
    87,
    88,
    89,
    90,
    91,
    92,
    93,
    94,
    95,
    96,
    97,
    98,
    99,
    100
   ],
   "LABELS": [
    "Random, changing",
    "$$$ Royal - Mashup (197)",
    "$$$ Royal - Mashup (220)",
    "$$$ Royal - Mashup (431)",
    "_Aderrasi - Wanderer in Curved Space - mash0000 - faclempt…",
    "_Geiss - Artifact 01",
    "_Geiss - Desert Rose 2",
    "_Geiss - untitled",
    "_Mig_049",
    "_Mig_085",
    "_Rovastar + Geiss - Hurricane Nightmare (Posterize Mix)",
    "Aderrasi + Geiss - Airhandler (Kali Mix) - Canvas Mix",
    "Aderrasi - Potion of Spirits",
    "Aderrasi - Songflower (Moss Posy)",
    "Aderrasi - Storm of the Eye (Thunder) - mash0000 - quasi p…",
    "An AdamFX n Martin Infusion 2 flexi - Why The Sky Looks Di…",
    "cope + martin - mother-of-pearl",
    "Cope - The Neverending Explosion of Red Liquid Fire",
    "Eo.S. + Phat - cubetrace - v2",
    "Eo.S. + Zylot - skylight (Stained Glass Majesty mix)",
    "Eo.S. - glowsticks v2 05 and proton lights (+Krash′s beat …",
    "fiShbRaiN + Flexi - witchcraft 2.0",
    "flexi + amandio c - organic [random mashup]",
    "flexi + amandio c - organic12-3d-2.milk",
    "Flexi + amandio c - piercing 05 - Kopie (2) - Kopie",
    "flexi + fishbrain - neon mindblob grafitti",
    "flexi + geiss - pogo cubes vs. tokamak vs. game of life [s…",
    "Flexi + Martin - astral projection",
    "Flexi + Martin - cascading decay swing",
    "Flexi + stahlregen - jelly showoff parade",
    "Flexi - alien fish pond",
    "Flexi - area 51",
    "flexi - bouncing balls [double mindblob neon mix]",
    "Flexi - infused with the spiral",
    "Flexi - mindblob [shiny mix]",
    "Flexi - mindblob mix",
    "flexi - mom, why the sky looks different today",
    "flexi - patternton, district of media, capitol of the unit…",
    "Flexi - predator-prey-spirals",
    "Flexi - smashing fractals [acid etching mix]",
    "flexi - swing out on the spiral",
    "Flexi - truly soft piece of software - this is generic tex…",
    "flexi - what is the matrix",
    "Flexi, fishbrain, Geiss + Martin - tokamak witchery",
    "Flexi, martin + geiss - dedicated to the sherwin maxawow",
    "Fumbling_Foo & Flexi, Martin, Orb, Unchained - Star Nova v7b",
    "Geiss + Flexi + Martin - disconnected",
    "Geiss - Cauldron - painterly 2 (saturation remix)",
    "Geiss - Reaction Diffusion 2",
    "Geiss - Spiral Artifact",
    "Geiss - Thumb Drum",
    "Geiss, Flexi + Stahlregen - Thumbdrum Tokamak [crossfiring…",
    "Goody - The Wild Vort",
    "high-altitude basket unraveling - singh grooves nitrogen a…",
    "Idiot - Star Of Annon",
    "Krash + Illusion - Spiral Movement",
    "martin + flexi - diamond cutter [prismaticvortex.com] - ca…",
    "Martin - acid wiring",
    "martin - angel flight",
    "martin - another kind of groove",
    "martin - bombyx mori",
    "martin - castle in the air",
    "martin - chain breaker",
    "Martin - charisma",
    "martin - disco mix 4",
    "martin - extreme heat",
    "martin - frosty caves 2",
    "martin - fruit machine",
    "martin - ghost city",
    "martin - glass corridor",
    "martin - infinity (2010 update)",
    "Martin - liquid arrows",
    "martin - mandelbox explorer - high speed demo version",
    "martin - mucus cervix",
    "Martin - QBikal - Surface Turbulence IIb",
    "martin - reflections on black tiles",
    "martin - stormy sea (2010 update)",
    "martin - The Bridge of Khazad-Dum",
    "martin - witchcraft reloaded",
    "martin [shadow harlequins shape code] - fata morgana",
    "martin, flexi, fishbrain + sto - enterstate [random mashup]",
    "Milk Artist At our Best - FED - SlowFast Ft AdamFX n Marti…",
    "ORB - Waaa",
    "Phat+fiShbRaiN+Eo.S_Mandala_Chasers_remix",
    "Rovastar + Loadus + Geiss - FractalDrop (Triple Mix)",
    "Rovastar - Oozing Resistance",
    "sawtooth grin roam",
    "shifter - dark tides bdrv mix 2",
    "suksma - heretical crosscut playpen",
    "suksma - Rovastar - Sunflower Passion (Enlightment Mix)_Ph…",
    "suksma - uninitialized variabowl (hydroponic chronic)",
    "suksma - vector exp 1 - couldn′t not",
    "TonyMilkdrop - Leonardo Da Vinci's Balloon [Flexi - merry-…",
    "TonyMilkdrop - Magellan's Nebula [Flexi - you enter first …",
    "Unchained & Rovastar - Wormhole Pillars (Hall of Shadows m…",
    "Unchained - Rewop",
    "Unchained - Unified Drag 2",
    "yin - 191 - Temporal singularities",
    "Zylot - Paint Spill (Music Reactive Paint Mix)",
    "Zylot - Star Ornament",
    "Zylot - True Visionary (Final Mix)"
   ]
  },
  {
   "NAME": "every",
   "TYPE": "float",
   "LABEL": "Change every (s)",
   "DEFAULT": 30,
   "MIN": 0,
   "MAX": 120
  },
  {
   "NAME": "blend",
   "TYPE": "float",
   "LABEL": "Blend (s)",
   "DEFAULT": 2.5,
   "MIN": 0,
   "MAX": 8
  },
  {
   "NAME": "shuffle",
   "TYPE": "bool",
   "LABEL": "Shuffle",
   "DEFAULT": true
  },
  {
   "NAME": "brightness",
   "TYPE": "float",
   "LABEL": "Brightness",
   "DEFAULT": 0.8,
   "MIN": 0.3,
   "MAX": 1
  }
 ]
}*/

// Ectodeck's built-in Milkdrop. It has no GLSL of its own: the header's
// RENDERER tells the deck plugin to draw it with projectM, the open-source
// Milkdrop engine built into the plugin (see the plugin's src/milkdrop.rs),
// from the hundred presets in the plugin's milkdrop folder, the same pack the
// web version used. The INPUTS are its settings, as for any shader.
